/**
 * x402 Cloud service: azzle-post-task
 * Paid unsigned calldata to open (post) a V2 task on one selected market.
 *
 * Distinct from azzle-open-tasks, which lists already-POSTED tasks.
 * x402 payment buys this preparation. It does not post, publish, or fund a task.
 */

// <generated-manifest>
// GENERATED by scripts/sync-manifest-surfaces.mjs. Do not edit.
export const BASE_MAINNET_MANIFEST = {
  "version": "2.0.0",
  "chainId": "8453",
  "market": "standard",
  "deploymentBlock": 49762587,
  "deployer": "0x56C1A78c58404B6C7356D4Aad3967859d8bc85E1",
  "governance": "0xB459145b74Ca4B198f73C0d573a161e85CA76D27",
  "factory": "0x386A99c2e6073a129482a2C92c92d196e123D843",
  "bundleHash": "0x4cdf297b3aee0f26d91edea41dc99f993f6729d6d8aae7cce1254a51d4ad6f61",
  "treasuryRouter": "0x0c89ed8e1f416e038c81f6Ba3335E302281bBAD3",
  "observationOracle": "0xA6EbECbe792c00D0b42a16B790Ab9fE356654C0A",
  "twapAdapter": "0xdBF2F47386Abb343b5c7C1613EFfec4F8Ae341B8",
  "usdOracle": "0xADF46968CdFAaB7298E470e475DF0DD88da02E7a",
  "pricingPolicy": "0xB386a02d6403a088723e502dC2bb78a6B699317A",
  "depositVault": "0x50fE780072d62E6bc07De096B6e58a141F385D2f",
  "escrowVault": "0xA10E05505A334963C44cd63cEcd204840D5122D1",
  "reputationRegistry": "0xb5827Bb3bb9760Ed72eA1416818188a8e71851B6",
  "verifierBondVault": "0xFeF0722d2f3ba0FEb59b3fd5dCAaF49e69BD5387",
  "stakingVault": "0xc39cA289303eAb7687B9D6A17b18538b75e7246b",
  "taskRegistry": "0xc59266071794210E68Be4c0CdB6D5F4CF652C300",
  "arbitrationModule": "0x1003592A2eeF71b15A21457910007b38B0e2027A",
  "usdcWethLeg": "0x186eE76400e08373Ea3F6184a11D8512bb8DA168",
  "exactInputExecutor": "0x1E343E3FDCC8f046E5C713dabf9226e281BD41A8",
  "paymentGateway": "0x16da063F3d99edB9920adeb9aaE55CfA32434e1C",
  "taskScopeRegistry": "0x2AB611C0fD3C8Cc91D1252ba99A37Fe7b977d964",
  "external": {
    "chainId": "8453",
    "usdc": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "weth": "0x4200000000000000000000000000000000000006",
    "azl": "0x931517E9502F9d52CDF6F5AC7fca7925e2A1BBA3",
    "poolManager": "0x498581fF718922c3f8e6A244956aF099B2652b2b",
    "universalRouter": "0x6fF5693b99212Da76ad316178A184AB56D299b43",
    "hook": "0xBDF938149ac6a781F94FAa0ed45E6A0e984c6544",
    "ethUsdFeed": "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70",
    "poolId": "0xaa7a431d1f79ea1f96f4299cce18267b278eb417bd8457b33f3be3c2645254ad"
  },
  "risk": {
    "governance": "0xB459145b74Ca4B198f73C0d573a161e85CA76D27",
    "burnRecipient": "0x41f35485Dea9e5e7C683d1C6CA650e8179c606ba",
    "minimumVerifierBondAzl": "10000000000000000000000",
    "stakingRewardDuration": 604800,
    "maxFeedAge": 3600,
    "twapWindow": 7200,
    "maxObservationGap": 900,
    "minimumActiveLiquidity": "500000000000000000000000",
    "evidenceWindow": 259200,
    "rulingWindow": 172800,
    "slashCapBps": 1000,
    "maxExecutionDeviationBps": 500,
    "creditContext": "0xe91d6ee3c1d1bdaac72313c14a9aed7f57d85be1424544bf74fe86adb3054f5a"
  },
  "actionCredits": {
    "activationRequired": true,
    "creditUnit": "1000000000000000000",
    "lifetimeCap": "600000000000000000000000",
    "baseStakeAzl": "100000000000000000000000000",
    "issuancePeriodSeconds": 2592000
  },
  "finalizedTx": "0xb19a2384139127ca4e9b30c30a365fa7a366f8f10d0effe0147365dc0265f146"
} as const;
export const BASE_MAINNET_MICRO_MANIFEST = {
  "version": "2.0.0",
  "chainId": "8453",
  "market": "micro",
  "deploymentBlock": 50246451,
  "deployer": "0x56C1A78c58404B6C7356D4Aad3967859d8bc85E1",
  "governance": "0xB459145b74Ca4B198f73C0d573a161e85CA76D27",
  "factory": "0x58e47667C41B4a0B43159Fae631c6010787AcF6c",
  "bundleHash": "0xd4fa04358b309a0dc29951a2a2510d64f08b98b7523f8c023011e858963c8d70",
  "treasuryRouter": "0x9B9f00560a1CA9fa1e2c59b66721d66EdC55ea4E",
  "observationOracle": "0xA6EbECbe792c00D0b42a16B790Ab9fE356654C0A",
  "twapAdapter": "0xdBF2F47386Abb343b5c7C1613EFfec4F8Ae341B8",
  "usdOracle": "0xADF46968CdFAaB7298E470e475DF0DD88da02E7a",
  "pricingPolicy": "0xDacD261dB8952e3d18537B3a61CA6dbB9fa3FA62",
  "depositVault": "0x64e254b99766BD163cFBAA4DAc74c1bfDFC93E82",
  "escrowVault": "0xfa84143a86383189Fd7a5f1a3637CD93F29441b0",
  "reputationRegistry": "0x549eABfaF6a4dC1E47B75f93a66352cCC3bfc074",
  "verifierBondVault": "0x54242151DDCe196314fba21FA630bF62D56a14B3",
  "stakingVault": "0x7d64483fC97481043a3eF407f9DDA2a1968BA43B",
  "taskRegistry": "0xd0dE9c0B928Fdd353213445e750a9526cBBba2B9",
  "arbitrationModule": "0x905E561B44E76fdeAF5F41Bc2c46ebCE4E5E02fE",
  "usdcWethLeg": "0x86695F1e51D090E845D9657F1f05b23D7d787694",
  "exactInputExecutor": "0xABBa41570D32CB7EFB4BBf6D3e08cC256ccDfdeA",
  "paymentGateway": "0xF4907910ae280767022A55C0F162eCb5B7DC7dec",
  "taskScopeRegistry": "0xdD8c6F7803CB46eB521960C827B52994bd35e863",
  "external": {
    "chainId": "8453",
    "usdc": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "weth": "0x4200000000000000000000000000000000000006",
    "azl": "0x931517E9502F9d52CDF6F5AC7fca7925e2A1BBA3",
    "poolManager": "0x498581fF718922c3f8e6A244956aF099B2652b2b",
    "universalRouter": "0x6fF5693b99212Da76ad316178A184AB56D299b43",
    "hook": "0xBDF938149ac6a781F94FAa0ed45E6A0e984c6544",
    "ethUsdFeed": "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70",
    "poolId": "0xaa7a431d1f79ea1f96f4299cce18267b278eb417bd8457b33f3be3c2645254ad"
  },
  "risk": {
    "governance": "0xB459145b74Ca4B198f73C0d573a161e85CA76D27",
    "burnRecipient": "0x41f35485Dea9e5e7C683d1C6CA650e8179c606ba",
    "minimumVerifierBondAzl": "1000000000000000000000",
    "stakingRewardDuration": 604800,
    "maxFeedAge": 3600,
    "twapWindow": 7200,
    "maxObservationGap": 900,
    "minimumActiveLiquidity": "500000000000000000000000",
    "evidenceWindow": 259200,
    "rulingWindow": 172800,
    "slashCapBps": 1000,
    "maxExecutionDeviationBps": 500,
    "creditContext": "0x7b571a45bf3d4d8ab7a250eb3284591d6aee3469222e0140d79991bbebb80360"
  },
  "actionCredits": {
    "activationRequired": true,
    "creditUnit": "1000000000000000000",
    "lifetimeCap": "6000000000000000000000000",
    "baseStakeAzl": "10000000000000000000000000",
    "issuancePeriodSeconds": 2592000
  },
  "finalizedTx": "0x2a13ce7eab7b10c822e81c02b039de497627aa175e43eb03e02b7ea77ccd40e0"
} as const;
export const BASE_MAINNET_MANIFESTS = {
  standard: BASE_MAINNET_MANIFEST,
  micro: BASE_MAINNET_MICRO_MANIFEST,
} as const;

export type AzzleMarket = keyof typeof BASE_MAINNET_MANIFESTS;

export function selectBaseMainnetManifest(market: AzzleMarket) {
  return BASE_MAINNET_MANIFESTS[market];
}
// </generated-manifest>

const RPC_CANDIDATES = [...new Set([
  process.env.BASE_RPC_URL,
  "https://mainnet.base.org",
  "https://base.llamarpc.com",
  "https://1rpc.io/base",
].filter(Boolean))];
const RPC_ATTEMPTS = 2;
const CHAIN_ID = 8453;
const MAX_TASK_DURATION = 30 * 24 * 60 * 60;
const MIN_TASK_DURATION = 60;
const MAX_SCOPE_BYTES = 8_192;
const POSTING_FLOOR_USD6 = { standard: 45_000_000n, micro: 5_000_000n } as const;
const MAX_TASK_USD6 = { standard: 10_000_000_000n, micro: 50_000_000n } as const;
const SELECTORS = {
  post: "0xcfa38d69",
  taskCount: "0xb6cb58a5",
  publish: "0x0560c7a8",
  quoteUsdForAzlPar: "0x45c1d35f",
  openTaskCapUsd6: "0x58178abb",
  isValid: "0xbb5d40eb",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function fail(error: unknown, extra: Record<string, unknown> = {}): Response {
  const message = error instanceof Error ? error.message : String(error);
  const status = /429|rate limit/i.test(message) ? 503 : 502;
  return json({ error: "upstream_unavailable", message, ...extra }, status);
}

async function sleep(ms: number) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

function retryable(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error);
  return /HTTP 429|HTTP 503|rate limit|did not return a Response/i.test(message);
}

async function rpc<T>(method: string, params: unknown[]): Promise<T> {
  let lastError: Error | undefined;
  for (const rpcUrl of RPC_CANDIDATES) {
    for (let attempt = 0; attempt < RPC_ATTEMPTS; attempt++) {
    if (attempt > 0) await sleep(200 * 2 ** (attempt - 1));
    try {
      const res = await fetch(rpcUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
      });
      if (!res.ok) {
        lastError = new Error(`Base RPC HTTP ${res.status}`);
        if (res.status === 429 || res.status >= 500) continue;
        throw lastError;
      }
      const payload = (await res.json()) as { result?: T; error?: { message: string } };
      if (payload.error || payload.result === undefined) {
        throw new Error(payload.error?.message ?? "Base RPC empty response");
      }
      return payload.result;
    } catch (error) {
      if (retryable(error)) {
        lastError = error instanceof Error ? error : new Error(String(error));
        continue;
      }
      throw error;
    }
    }
  }
  throw lastError ?? new Error("Base RPC unavailable");
}

function encodeUint(value: bigint): string {
  return value.toString(16).padStart(64, "0");
}

function encodeBytes(data: Uint8Array): string {
  const length = encodeUint(BigInt(data.length));
  let hex = "";
  for (const byte of data) hex += byte.toString(16).padStart(2, "0");
  const pad = (64 - (hex.length % 64)) % 64;
  return length + hex + "0".repeat(pad);
}

function encodePublish(taskId: bigint, scope: string): string {
  const bytes = new TextEncoder().encode(scope);
  return `${SELECTORS.publish}${encodeUint(taskId)}${encodeUint(64n)}${encodeBytes(bytes)}`;
}

function asString(value: unknown): string | undefined {
  if (value == null) return undefined;
  if (typeof value === "string") return value;
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return undefined;
}

async function readParams(req: Request): Promise<Record<string, string>> {
  const out: Record<string, string> = {};
  for (const [key, value] of new URL(req.url).searchParams) out[key] = value;
  if (req.method === "POST" || req.method === "PUT" || req.method === "PATCH") {
    const text = await req.text();
    if (text.trim()) {
      try {
        const body = JSON.parse(text) as Record<string, unknown>;
        if (body && typeof body === "object") {
          for (const [key, value] of Object.entries(body)) {
            const encoded = asString(value);
            if (encoded !== undefined) out[key] = encoded;
          }
        }
      } catch (error) {
        if (error instanceof SyntaxError) throw json({ error: "invalid_json" }, 400);
        throw error;
      }
    }
  }
  return out;
}

function parseUint(raw: string | undefined, name: string): bigint | undefined {
  if (raw == null || raw.trim() === "") return undefined;
  const value = raw.trim();
  if (!/^[0-9]+$/.test(value)) {
    throw json({ error: "invalid_uint", field: name, hint: `${name} must be a non-negative decimal integer` }, 400);
  }
  return BigInt(value);
}

export default async function handler(req: Request) {
  try {
    let params: Record<string, string>;
    try {
      params = await readParams(req);
    } catch (error) {
      if (error instanceof Response) return error;
      throw error;
    }

    const market = params.market;
    if (market !== "standard" && market !== "micro") {
      return json({ error: "invalid_market", hint: "pass market=standard|micro" }, 400);
    }

    let totalAmount: bigint | undefined;
    let durationSeconds: bigint | undefined;
    let deadlineInput: bigint | undefined;
    try {
      totalAmount = parseUint(params.totalAmount, "totalAmount");
      durationSeconds = parseUint(params.durationSeconds, "durationSeconds");
      deadlineInput = parseUint(params.deadline, "deadline");
    } catch (error) {
      if (error instanceof Response) return error;
      throw error;
    }
    if (totalAmount === undefined || totalAmount === 0n) {
      return json({
        error: "missing_total_amount",
        hint: "pass totalAmount as AZL wei (decimal integer string)",
      }, 400);
    }

    const now = Math.floor(Date.now() / 1000);
    let deadline: number;
    if (deadlineInput !== undefined) {
      deadline = Number(deadlineInput);
    } else if (durationSeconds !== undefined) {
      deadline = now + Number(durationSeconds);
    } else {
      return json({
        error: "missing_deadline",
        hint: "pass durationSeconds (60..2592000) or deadline (unix seconds within 30 days)",
      }, 400);
    }
    if (!Number.isSafeInteger(deadline) || deadline < now + MIN_TASK_DURATION || deadline > now + MAX_TASK_DURATION - MIN_TASK_DURATION) {
      return json({
        error: "invalid_deadline",
        hint: "task deadline must be at least 60 seconds and at most 30 days from now",
      }, 400);
    }

    const scope = (params.scope ?? params.scopeText ?? "").trim();
    if (scope) {
      const scopeBytes = new TextEncoder().encode(scope);
      if (scopeBytes.length === 0 || scopeBytes.length > MAX_SCOPE_BYTES) {
        return json({ error: "invalid_scope", hint: "public scope must be 1..8192 UTF-8 bytes" }, 400);
      }
    }

    const manifest = selectBaseMainnetManifest(market as AzzleMarket);
    const registryAddress = manifest.taskRegistry;
    const scopeRegistry = manifest.taskScopeRegistry;
    const usdOracle = manifest.usdOracle;

    const validRaw = await rpc<string>("eth_call", [{ to: usdOracle, data: SELECTORS.isValid }, "latest"]);
    const openCapRaw = await rpc<string>("eth_call", [{ to: registryAddress, data: SELECTORS.openTaskCapUsd6 }, "latest"]);
    const amountUsdRaw = await rpc<string>("eth_call", [{
      to: usdOracle,
      data: `${SELECTORS.quoteUsdForAzlPar}${encodeUint(totalAmount)}`,
    }, "latest"]);
    const taskCountRaw = await rpc<string>("eth_call", [{ to: registryAddress, data: SELECTORS.taskCount }, "latest"]);

    if (BigInt(validRaw || "0x0") === 0n) {
      return json({ error: "oracle_invalid", market, hint: "usdOracle.isValid() is false" }, 503);
    }

    const maxTaskUsd6 = MAX_TASK_USD6[market];
    const openTaskCapUsd6 = BigInt(openCapRaw || "0x0");
    const amountUsd6 = BigInt(amountUsdRaw || "0x0");
    if (amountUsd6 === 0n) {
      return json({ error: "quote_unavailable", market }, 503);
    }
    if (amountUsd6 > maxTaskUsd6 || amountUsd6 > openTaskCapUsd6) {
      return json({
        error: "task_cap",
        market,
        amountUsd6: amountUsd6.toString(),
        maxTaskUsd6: maxTaskUsd6.toString(),
        openTaskCapUsd6: openTaskCapUsd6.toString(),
      }, 400);
    }

    const expectedLocalId = BigInt(taskCountRaw || "0x0") + 1n;
    const expectedTaskId = `v2:${market}:${expectedLocalId.toString()}`;
    const postData = `${SELECTORS.post}${encodeUint(totalAmount)}${encodeUint(BigInt(deadline))}`;
    const transactions = [
      { step: "post", to: registryAddress, data: postData, value: "0x0", chainId: CHAIN_ID },
    ];
    if (scope) {
      transactions.push({
        step: "publish-scope",
        to: scopeRegistry,
        data: encodePublish(expectedLocalId, scope),
        value: "0x0",
        chainId: CHAIN_ID,
      });
    }

    return json({
      protocol: "azzle",
      chainId: CHAIN_ID,
      network: "base",
      market,
      action: "post-task",
      unsigned: true,
      executesOnchain: false,
      note: "x402 payment buys this unsigned batch. It does not post or fund the task. Sign and submit on Base. post() reserves the access fee from the deposit vault; job escrow is a later fund() of AZL.",
      atomicRequired: Boolean(scope),
      expectedTaskId,
      expectedLocalId: expectedLocalId.toString(),
      concurrentPostWarning: scope
        ? "publish uses taskCount()+1; a concurrent post can shift the id and revert publish. Re-prepare if that happens."
        : undefined,
      registryAddress,
      taskScopeRegistry: scope ? scopeRegistry : undefined,
      totalAmountAzlWei: totalAmount.toString(),
      amountUsd6: amountUsd6.toString(),
      maxTaskUsd6: maxTaskUsd6.toString(),
      openTaskCapUsd6: openTaskCapUsd6.toString(),
      postingFloorUsd6: POSTING_FLOOR_USD6[market].toString(),
      deadline,
      publicScope: scope || null,
      transactions,
      generatedAt: now,
    });
  } catch (error) {
    if (error instanceof Response) return error;
    return fail(error);
  }
}
