/**
 * x402 Cloud service: azzle-leaderboard
 * Paid leaderboard — market-specific canonical reputation counters or AZL
 * verifier bonds for subjects discovered in a bounded event window.
 *
 * Self-contained handler (per-service bundle): only the generated manifest is imported.
 * Price + schema live in ../../bankr.x402.json.
 *
 * @see docs/X402_CLOUD.md
 */
// <generated-manifest>
// GENERATED by scripts/sync-manifest-surfaces.mjs. Do not edit.
export const BASE_MAINNET_MANIFEST = {
  "version": "2.0.0",
  "chainId": "8453",
  "market": "standard",
  "deploymentBlock": 49762587,
  "deployer": "0x56C1A78c58404B6C7356D4Aad3967859d8bc85E1",
  "governance": "0xB459145b74Ca4B198f73C0d573a161e85CA76D27",
  "factory": "0x386A99c2e6073a129482a2C92c92d196e123D843",
  "bundleHash": "0x4cdf297b3aee0f26d91edea41dc99f993f6729d6d8aae7cce1254a51d4ad6f61",
  "treasuryRouter": "0x0c89ed8e1f416e038c81f6Ba3335E302281bBAD3",
  "observationOracle": "0xA6EbECbe792c00D0b42a16B790Ab9fE356654C0A",
  "twapAdapter": "0xdBF2F47386Abb343b5c7C1613EFfec4F8Ae341B8",
  "usdOracle": "0xADF46968CdFAaB7298E470e475DF0DD88da02E7a",
  "pricingPolicy": "0xB386a02d6403a088723e502dC2bb78a6B699317A",
  "depositVault": "0x50fE780072d62E6bc07De096B6e58a141F385D2f",
  "escrowVault": "0xA10E05505A334963C44cd63cEcd204840D5122D1",
  "reputationRegistry": "0xb5827Bb3bb9760Ed72eA1416818188a8e71851B6",
  "verifierBondVault": "0xFeF0722d2f3ba0FEb59b3fd5dCAaF49e69BD5387",
  "stakingVault": "0xc39cA289303eAb7687B9D6A17b18538b75e7246b",
  "taskRegistry": "0xc59266071794210E68Be4c0CdB6D5F4CF652C300",
  "arbitrationModule": "0x1003592A2eeF71b15A21457910007b38B0e2027A",
  "usdcWethLeg": "0x186eE76400e08373Ea3F6184a11D8512bb8DA168",
  "exactInputExecutor": "0x1E343E3FDCC8f046E5C713dabf9226e281BD41A8",
  "paymentGateway": "0x16da063F3d99edB9920adeb9aaE55CfA32434e1C",
  "taskScopeRegistry": "0x2AB611C0fD3C8Cc91D1252ba99A37Fe7b977d964",
  "external": {
    "chainId": "8453",
    "usdc": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "weth": "0x4200000000000000000000000000000000000006",
    "azl": "0x931517E9502F9d52CDF6F5AC7fca7925e2A1BBA3",
    "poolManager": "0x498581fF718922c3f8e6A244956aF099B2652b2b",
    "universalRouter": "0x6fF5693b99212Da76ad316178A184AB56D299b43",
    "hook": "0xBDF938149ac6a781F94FAa0ed45E6A0e984c6544",
    "ethUsdFeed": "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70",
    "poolId": "0xaa7a431d1f79ea1f96f4299cce18267b278eb417bd8457b33f3be3c2645254ad"
  },
  "risk": {
    "governance": "0xB459145b74Ca4B198f73C0d573a161e85CA76D27",
    "burnRecipient": "0x41f35485Dea9e5e7C683d1C6CA650e8179c606ba",
    "minimumVerifierBondAzl": "10000000000000000000000",
    "stakingRewardDuration": 604800,
    "maxFeedAge": 3600,
    "twapWindow": 7200,
    "maxObservationGap": 900,
    "minimumActiveLiquidity": "500000000000000000000000",
    "evidenceWindow": 259200,
    "rulingWindow": 172800,
    "slashCapBps": 1000,
    "maxExecutionDeviationBps": 500,
    "creditContext": "0xe91d6ee3c1d1bdaac72313c14a9aed7f57d85be1424544bf74fe86adb3054f5a"
  },
  "actionCredits": {
    "activationRequired": true,
    "creditUnit": "1000000000000000000",
    "lifetimeCap": "600000000000000000000000",
    "baseStakeAzl": "100000000000000000000000000",
    "issuancePeriodSeconds": 2592000
  },
  "finalizedTx": "0xb19a2384139127ca4e9b30c30a365fa7a366f8f10d0effe0147365dc0265f146"
} as const;
export const BASE_MAINNET_MICRO_MANIFEST = {
  "version": "2.0.0",
  "chainId": "8453",
  "market": "micro",
  "deploymentBlock": 50246451,
  "deployer": "0x56C1A78c58404B6C7356D4Aad3967859d8bc85E1",
  "governance": "0xB459145b74Ca4B198f73C0d573a161e85CA76D27",
  "factory": "0x58e47667C41B4a0B43159Fae631c6010787AcF6c",
  "bundleHash": "0xd4fa04358b309a0dc29951a2a2510d64f08b98b7523f8c023011e858963c8d70",
  "treasuryRouter": "0x9B9f00560a1CA9fa1e2c59b66721d66EdC55ea4E",
  "observationOracle": "0xA6EbECbe792c00D0b42a16B790Ab9fE356654C0A",
  "twapAdapter": "0xdBF2F47386Abb343b5c7C1613EFfec4F8Ae341B8",
  "usdOracle": "0xADF46968CdFAaB7298E470e475DF0DD88da02E7a",
  "pricingPolicy": "0xDacD261dB8952e3d18537B3a61CA6dbB9fa3FA62",
  "depositVault": "0x64e254b99766BD163cFBAA4DAc74c1bfDFC93E82",
  "escrowVault": "0xfa84143a86383189Fd7a5f1a3637CD93F29441b0",
  "reputationRegistry": "0x549eABfaF6a4dC1E47B75f93a66352cCC3bfc074",
  "verifierBondVault": "0x54242151DDCe196314fba21FA630bF62D56a14B3",
  "stakingVault": "0x7d64483fC97481043a3eF407f9DDA2a1968BA43B",
  "taskRegistry": "0xd0dE9c0B928Fdd353213445e750a9526cBBba2B9",
  "arbitrationModule": "0x905E561B44E76fdeAF5F41Bc2c46ebCE4E5E02fE",
  "usdcWethLeg": "0x86695F1e51D090E845D9657F1f05b23D7d787694",
  "exactInputExecutor": "0xABBa41570D32CB7EFB4BBf6D3e08cC256ccDfdeA",
  "paymentGateway": "0xF4907910ae280767022A55C0F162eCb5B7DC7dec",
  "taskScopeRegistry": "0xdD8c6F7803CB46eB521960C827B52994bd35e863",
  "external": {
    "chainId": "8453",
    "usdc": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "weth": "0x4200000000000000000000000000000000000006",
    "azl": "0x931517E9502F9d52CDF6F5AC7fca7925e2A1BBA3",
    "poolManager": "0x498581fF718922c3f8e6A244956aF099B2652b2b",
    "universalRouter": "0x6fF5693b99212Da76ad316178A184AB56D299b43",
    "hook": "0xBDF938149ac6a781F94FAa0ed45E6A0e984c6544",
    "ethUsdFeed": "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70",
    "poolId": "0xaa7a431d1f79ea1f96f4299cce18267b278eb417bd8457b33f3be3c2645254ad"
  },
  "risk": {
    "governance": "0xB459145b74Ca4B198f73C0d573a161e85CA76D27",
    "burnRecipient": "0x41f35485Dea9e5e7C683d1C6CA650e8179c606ba",
    "minimumVerifierBondAzl": "1000000000000000000000",
    "stakingRewardDuration": 604800,
    "maxFeedAge": 3600,
    "twapWindow": 7200,
    "maxObservationGap": 900,
    "minimumActiveLiquidity": "500000000000000000000000",
    "evidenceWindow": 259200,
    "rulingWindow": 172800,
    "slashCapBps": 1000,
    "maxExecutionDeviationBps": 500,
    "creditContext": "0x7b571a45bf3d4d8ab7a250eb3284591d6aee3469222e0140d79991bbebb80360"
  },
  "actionCredits": {
    "activationRequired": true,
    "creditUnit": "1000000000000000000",
    "lifetimeCap": "6000000000000000000000000",
    "baseStakeAzl": "10000000000000000000000000",
    "issuancePeriodSeconds": 2592000
  },
  "finalizedTx": "0x2a13ce7eab7b10c822e81c02b039de497627aa175e43eb03e02b7ea77ccd40e0"
} as const;
export const BASE_MAINNET_MANIFESTS = {
  standard: BASE_MAINNET_MANIFEST,
  micro: BASE_MAINNET_MICRO_MANIFEST,
} as const;

export type AzzleMarket = keyof typeof BASE_MAINNET_MANIFESTS;

export function selectBaseMainnetManifest(market: AzzleMarket) {
  return BASE_MAINNET_MANIFESTS[market];
}
// </generated-manifest>

const RPC_CANDIDATES = [...new Set([
  process.env.BASE_RPC_URL,
  "https://mainnet.base.org",
  "https://base.llamarpc.com",
  "https://1rpc.io/base",
].filter(Boolean))];
const RPC_ATTEMPTS = 2;
const EVENT_SCAN_WINDOW = 12_000n;
const LOG_CHUNK_SIZE = 10_000n;
const MAX_CANDIDATES = 250;
const ZERO = "0x0000000000000000000000000000000000000000";
const REPUTATION_OF = "0xb9f79451";
const BONDS = "0xfe10d774";
const TOPICS = {
  completion: "0xc4a3b89ce948af8aeadaeedb0045888a7d240292c45ebda88c0b753951036d03",
  dispute: "0xaf5ae1bca4608375b51171e75330b6ca2585c77ef9f2e76e5152cbf9be0983d6",
  posterExpiry: "0x2a890b93401bb57abd6b8e3d0d45f508726e5eab0e2f7334144d07a3f366342e",
  unresolved: "0x1308dbcf993f5a57940396dde8ec9aa80a78ac5700d9267de955c07e4ee5a36a",
  bonded: "0xd0a009034e24a39106653c4903cf28b1947b8a9964d03206648e0f0a5de74a46",
  withdrawn: "0x7084f5476618d8e60b11ef0d7d3f06914655adb8793e28ff7f018d4c76d505d5",
  slashed: "0x96e0041f14ae401fab2384e3c29da20cb0263ef760c47847db1f13403cea654c",
} as const;

type RpcLog = { data: string; topics: string[] };

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function fail(error: unknown, extra: Record<string, unknown> = {}): Response {
  const message = error instanceof Error ? error.message : String(error);
  const status = /429|rate limit/i.test(message) ? 503 : 502;
  return json({ error: "upstream_unavailable", message, ...extra }, status);
}

async function sleep(ms: number) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

function retryable(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error);
  return /HTTP 429|HTTP 503|rate limit|did not return a Response/i.test(message);
}

async function rpc<T>(method: string, params: unknown[]): Promise<T> {
  let lastError: Error | undefined;
  for (const rpcUrl of RPC_CANDIDATES) {
    for (let attempt = 0; attempt < RPC_ATTEMPTS; attempt++) {
    if (attempt > 0) await sleep(200 * 2 ** (attempt - 1));
    try {
      const response = await fetch(rpcUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
      });
      if (!response.ok) {
        lastError = new Error(`Base RPC HTTP ${response.status}`);
        if (response.status === 429 || response.status >= 500) continue;
        throw lastError;
      }
      const payload = await response.json() as { result?: T; error?: { message: string } };
      if (payload.error || payload.result === undefined) {
        throw new Error(payload.error?.message ?? "Base RPC empty response");
      }
      return payload.result;
    } catch (error) {
      if (retryable(error)) {
        lastError = error instanceof Error ? error : new Error(String(error));
        continue;
      }
      throw error;
    }
    }
  }
  throw lastError ?? new Error("Base RPC unavailable");
}

function blockTag(block: bigint): string {
  return `0x${block.toString(16)}`;
}

function topicAddress(topic?: string): string | null {
  if (!topic || topic.length !== 66) return null;
  const address = `0x${topic.slice(-40)}`.toLowerCase();
  return address === ZERO ? null : address;
}

function dataAddress(data: string, wordIndex: number): string | null {
  const start = 2 + wordIndex * 64;
  return topicAddress(`0x${data.slice(start, start + 64)}`);
}

function addressArg(address: string): string {
  return address.slice(2).padStart(64, "0");
}

function compareBigInt(left: string, right: string): number {
  const a = BigInt(left);
  const b = BigInt(right);
  return a === b ? 0 : a > b ? 1 : -1;
}

async function mapInBatches<T, U>(
  values: T[],
  batchSize: number,
  map: (value: T) => Promise<U>,
): Promise<U[]> {
  const results: U[] = [];
  for (let index = 0; index < values.length; index += batchSize) {
    results.push(...await Promise.all(values.slice(index, index + batchSize).map(map)));
    if (index + batchSize < values.length) await sleep(80);
  }
  return results;
}

async function getLogs(
  address: string,
  eventTopics: string[],
  fromBlock: bigint,
  toBlock: bigint,
): Promise<RpcLog[]> {
  const logs: RpcLog[] = [];
  for (let from = fromBlock; from <= toBlock; from += LOG_CHUNK_SIZE) {
    const to = from + LOG_CHUNK_SIZE - 1n > toBlock ? toBlock : from + LOG_CHUNK_SIZE - 1n;
    logs.push(...await rpc<RpcLog[]>("eth_getLogs", [{
      address,
      fromBlock: blockTag(from),
      toBlock: blockTag(to),
      topics: [eventTopics],
    }]));
    if (to < toBlock) await sleep(80);
  }
  return logs;
}

function discoverReputationSubjects(logs: RpcLog[]): string[] {
  const subjects = new Set<string>();
  for (const log of logs) {
    const topic = log.topics[0]?.toLowerCase();
    if (topic === TOPICS.completion || topic === TOPICS.posterExpiry) {
      for (const value of [topicAddress(log.topics[2]), topicAddress(log.topics[3])]) {
        if (value) subjects.add(value);
      }
    } else if (topic === TOPICS.unresolved) {
      const poster = topicAddress(log.topics[2]);
      if (poster) subjects.add(poster);
    } else if (topic === TOPICS.dispute) {
      for (const value of [dataAddress(log.data, 0), dataAddress(log.data, 1)]) {
        if (value) subjects.add(value);
      }
    }
  }
  return [...subjects];
}

function discoverVerifierSubjects(logs: RpcLog[]): string[] {
  const subjects = new Set<string>();
  for (const log of logs) {
    const verifier = topicAddress(log.topics[1]);
    if (verifier) subjects.add(verifier);
  }
  return [...subjects];
}

export default async function handler(req: Request) {
  try {
    const params = new URL(req.url).searchParams;
    const market = params.get("market");
    if (market !== "standard" && market !== "micro") {
      return json({ error: "invalid_market", hint: "pass ?market=standard|micro" }, 400);
    }
    const kind = (params.get("kind") ?? "reputation").toLowerCase();
    const raw = Number(params.get("limit") ?? "25");
    const limit = Number.isFinite(raw) ? Math.min(Math.max(Math.trunc(raw), 1), 100) : 25;

    if (kind !== "reputation" && kind !== "verifiers") {
      return json({ error: "invalid_kind", hint: "kind=reputation|verifiers" }, 400);
    }

    const manifest = selectBaseMainnetManifest(market);
    const latestBlock = BigInt(await rpc<string>("eth_blockNumber", []));
    const deploymentBlock = BigInt(manifest.deploymentBlock);
    const windowStart = latestBlock >= EVENT_SCAN_WINDOW - 1n
      ? latestBlock - EVENT_SCAN_WINDOW + 1n
      : 0n;
    const fromBlock = deploymentBlock > windowStart ? deploymentBlock : windowStart;
    const eventTopics = kind === "reputation"
      ? [TOPICS.completion, TOPICS.dispute, TOPICS.posterExpiry, TOPICS.unresolved]
      : [TOPICS.bonded, TOPICS.withdrawn, TOPICS.slashed];
    const sourceAddress = kind === "reputation"
      ? manifest.reputationRegistry
      : manifest.verifierBondVault;
    const logs = await getLogs(sourceAddress, eventTopics, fromBlock, latestBlock);
    const discovered = kind === "reputation"
      ? discoverReputationSubjects(logs)
      : discoverVerifierSubjects(logs);
    const candidateLimited = discovered.length > MAX_CANDIDATES;
    const candidates = discovered.slice(-MAX_CANDIDATES);
    const snapshot = blockTag(latestBlock);

    const rows = kind === "reputation"
      ? await mapInBatches(candidates, 5, async (address) => {
          const result = await rpc<string>("eth_call", [{
            to: manifest.reputationRegistry,
            data: `${REPUTATION_OF}${addressArg(address)}`,
          }, snapshot]);
          const words = result.slice(2).match(/.{64}/g) ?? [];
          return {
            address,
            completed: BigInt(`0x${words[0] ?? "0"}`).toString(),
            wins: BigInt(`0x${words[1] ?? "0"}`).toString(),
            losses: BigInt(`0x${words[2] ?? "0"}`).toString(),
          };
        }).then((values) => values.sort((a, b) =>
          compareBigInt(b.completed, a.completed)
          || compareBigInt(b.wins, a.wins)
          || compareBigInt(a.losses, b.losses)
          || a.address.localeCompare(b.address)
        ))
      : await mapInBatches(candidates, 5, async (address) => ({
          address,
          bondAzlWei: BigInt(await rpc<string>("eth_call", [{
            to: manifest.verifierBondVault,
            data: `${BONDS}${addressArg(address)}`,
          }, snapshot])).toString(),
        })).then((values) => values
          .filter((row) => BigInt(row.bondAzlWei) > 0n)
          .sort((a, b) =>
            compareBigInt(b.bondAzlWei, a.bondAzlWei)
            || a.address.localeCompare(b.address)
          ));

    return json({
      protocol: "azzle",
      chainId: 8453,
      market,
      kind,
      count: Math.min(rows.length, limit),
      agents: rows.slice(0, limit),
      source: "base-rpc-events-and-views",
      sourceAddress,
      snapshotBlock: latestBlock.toString(),
      indexWindow: {
        fromBlock: fromBlock.toString(),
        toBlock: latestBlock.toString(),
        deploymentBlock: deploymentBlock.toString(),
        eventCount: logs.length,
        discoveredCandidates: discovered.length,
        indexedCandidates: candidates.length,
        candidateLimit: MAX_CANDIDATES,
        windowTruncated: fromBlock > deploymentBlock,
        candidateTruncated: candidateLimited,
        complete: fromBlock === deploymentBlock && !candidateLimited,
      },
      ranking: kind === "reputation"
        ? "completed desc, wins desc, losses asc"
        : "bondAzlWei desc",
      generatedAt: Math.floor(Date.now() / 1000),
    });
  } catch (error) {
    if (error instanceof Response) return error;
    return fail(error);
  }
}
